en_us.langからのズレと不足TODO付け
GTModpackTeam/GregTech pull request #10
Opened 2023-01-17 13:46 UTC by tier940

2023-01-17 13:50 UTC, tier940 commented
題名のとおりです、よろしくお願い致します

2023-01-17 13:54 UTC, MrKono commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> -gregtech.advancement.steam.6_bronze_alloy_smelter.name=I have a pen. I have an apple...
これ確かワザとのはずです

2023-01-17 15:23 UTC, tier940 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> -gregtech.advancement.steam.6_bronze_alloy_smelter.name=I have a pen. I have an apple...
そうでした...

2023-01-30 05:49 UTC, Quarri6343 requested changes

2023-01-30 05:49 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.machine.assembler.lv.tooltip=野郎共, 組立だ!
[アベンジャーズ、アッセンブル！](https://weekend-cinema.com/20957/)

2023-01-30 05:49 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.machine.bender.lv.tooltip=ブー, 彼は悪いやつだ! 彼は酒に浸りたいんだ!!!
元ネタ[これ](https://en.wikipedia.org/wiki/Bender_(Futurama))です
直訳しようがないので意訳するとこうなります：

俺達にはひんまがっててマシーンみたいな奴が必要だ！

2023-01-30 05:49 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.machine.extractor.lv.tooltip=ドゥームのデジューサーデバイス-D123
終末の果汁絞り器

2023-01-30 05:49 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.machine.forge_hammer.lv.tooltip=ハンマーで殴るのをやめるんだ!
翻訳しません(英語のまま)。
元ネタは[この曲のこのシーン](https://youtu.be/otCpCn0l4Wo?t=172)で、会話の流れをぶったぎって別の会話に持っていくときによく使われます。
ちなみにGTCEuの中国語翻訳でも同じ理由で翻訳されてません

2023-01-30 05:49 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.advancement.steam.6_bronze_alloy_smelter.name=合金製錬炉を作成する.
二つのものを合わせて一つにする->PPAP

2023-01-30 05:53 UTC, tier940 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.machine.forge_hammer.lv.tooltip=ハンマーで殴るのをやめるんだ!
@Quarri6343 
日本ネタとして `君がッ曲がるまで殴るのをやめないッ!` でもよいかなと思ったけどどうだろ？

2023-01-30 05:56 UTC, MrKono commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.advancement.steam.6_bronze_alloy_smelter.name=合金製錬炉を作成する.
「I have a pen. I have an apple...」を続投か、「二つのものを合わせて一つにする->PPAP」に変更か、どちらがいいでしょうか？

2023-02-03 15:39 UTC, Quarri6343 approved these changes

2023-02-04 02:57 UTC, tier940 commented
CEuにPRを投げるため一旦クローズ

2023-02-04 02:57 UTC, closed without merging