Ja jp
GTModpackTeam/GregTech pull request #11
Opened 2023-02-12 05:39 UTC by MrKono

## What
2.5.0以降のの更新に対応しました

2023-02-12 06:04 UTC, Quarri6343 requested changes

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +cover.voiding.tooltip=§c警告!§7 これを"有効"にするということは液体やアイテムが消去されることを意味します。
§c警告!§7 これを"有効"にすると搬入された液体やアイテムが全て消去されます。

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +metaitem.cover.fluid.detector.advanced.tooltip=§f液体保管量§7に基づいた§fRSラッチ§7を与える§fカバー§7
§fSRラッチ§7で制御された§f液体保管量§7をレッドストーン信号として与える§fカバー§7

(日本語ではSRラッチと呼ぶらしい)

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +metaitem.cover.item.detector.advanced.tooltip=§fアイテム保管量§7に基づいた§fRSラッチ§7を与える§fカバー§7
同上

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.machine.charcoal_pile.tooltip.1=§c点火されている§7時、原木を§a木炭§7に変化させる。
§c点火される§7と、時間をかけて原木を§a木炭§7に変化させる。

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.multiblock.charcoal_pile.description=最大9×4×9の範囲の原木を脆い木炭に変える。\n\n窯の床はレンガブロックでなければならないが、壁や屋根には地盤に関連するあらゆるブロックが使用できる。窯内に空気があってはならない。\n\n大きな窯は原木の変換により時間がかかるがより効率的である。
最大9×4×9の範囲の原木を脆い木炭に変える。\n\n窯の床はレンガブロックでなければならないが、壁や屋根には地面に関連するあらゆるブロックが使用できる。窯内に空気があってはならない。\n\n大きな窯を作ると原木の変換により時間がかかるようになるが、より効率的である。

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.machine.charcoal_pile.tooltip=地下の燃料屋さん
アングラな燃料工場

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +terminal.store.match=インベントリで必要なアイテムが検出されました。アプリをインストール/アップグレードを行いますか？
インベントリで必要なアイテムが検出されました。アプリのインストール/アップグレードを行いますか？

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.bus.collapse.error=第一にバスはマルチブロックを一部分でなければならない
バスをマルチブロックに接続してください

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.jei.ore.biome_weighting_title=§dバイオーム修飾による生成頻度:
バイオームによる倍率がかかった生成頻度の合計：

2023-02-12 06:04 UTC, Quarri6343 commented on src/main/resources/assets/gregtech/lang/ja_jp.lang
> +gregtech.jei.fluid.weight_hover=液体脈の生成頻度。液体をマウスオーバーすることでバイオーム修飾の影響を確認できる。
液体脈の生成頻度。液体をマウスオーバーすることでバイオームによる倍率の影響を確認できる。

2023-02-14 06:14 UTC, Quarri6343 approved these changes

2023-02-14 06:19 UTC, tier940 commented
CEuにPRを投げるため一旦クローズ

2023-02-14 06:44 UTC, merged